#pragma once

#include "NativeGameplayTags.h"

namespace HodgeAlsViewModeTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FirstPerson)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThirdPerson)
}

namespace HodgeAlsLocomotionModeTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Grounded)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
}

namespace HodgeAlsRotationModeTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VelocityDirection)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewDirection)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Aiming)
}

namespace HodgeAlsStanceTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standing)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Crouching)
}

namespace HodgeAlsGaitTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Running)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting)
}

namespace HodgeAlsOverlayModeTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}

namespace HodgeAlsLocomotionActionTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rolling)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantling)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdolling)
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GettingUp)
}

namespace HodgeAlsGroundedEntryModeTags
{
	HODGEPODGE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FromRoll)
}
